services:
  - type: web
    name: qcbot
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn qcbot:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
    envVarGroups:
      - name: Basecamp API
      - name: Groq API
